version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update
            sudo apt-get -y install curl
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo bash -
            sudo apt-get install -y libsqlite3-dev nodejs python3 python3-venv python3-pip gcc g++ make

            npm install
            python3 -m venv .python3-environment
            . .python3-environment/bin/activate
            pip3 install -r requirements.txt

            npm run lint
            python3 -m black --check falert/backend
            python3 -m pylint falert/backend
            python3 -m mypy falert/backend
